preisvergleich/urls.py
from django.urls import path

from .views import (
    category_detail_view,
    category_editor_view,
    helper_views,
    index_view,
    product_editor_view,
)

app_name = "preisvergleich"

# fmt: off
urlpatterns = [
    # Index view
    path("", index_view.index, name="index"),

    # Helper views
    path("delete_error_message", helper_views.delete_error_message, name="delete_error_message"),

    # Category editor views
    path("category_editor/", category_editor_view.category_editor, name="category_editor"),
    path("category_editor/new", category_editor_view.create_new_category, name="create_new_category"),

    # Category detail view
    path("category_detail/<int:category_id>", category_detail_view.category_detail, name="category_detail"),

    # Product editor views
    path("product_editor/<int:category_id>", product_editor_view.product_editor, name="product_editor"),
    path("product_editor/<int:category_id>/new", product_editor_view.create_new_product, name="create_new_product"),
]
# fmt: on

webapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("preisvergleich.urls")),
    path("admin/", admin.site.urls),
]

preisvergleich/models.py
from django.core.validators import MinValueValidator
from django.db import models


class Category(models.Model):
    """
    The Category model.

    Attributes
    ----------
    name : CharField
        The name of the Category

    """

    name = models.CharField(max_length=32)

    def __str__(self) -> str:
        """Return a string representation of the Category."""
        return self.name


class Product(models.Model):
    """
    The Product model.

    Attributes
    ----------
    category : ForeignKey
        The associated Category
    name : CharField
        The name of the product
    shop : CharField
        The shop the product can be found
    url : URLField
        The url to the product
    weight : IntegerField
        The weight of the product
    price : DecimalField
        The price of the product

    """

    class Shops(models.TextChoices):
        """Shop Choices Enum."""

        BILLA = "Billa"
        HOFER = "Hofer"

    category = models.ForeignKey(
        "Category",
        on_delete=models.DO_NOTHING,
    )
    name = models.CharField(max_length=32)
    shop = models.CharField(max_length=32, choices=Shops.choices, default=Shops.HOFER)
    url = models.URLField()
    weight = models.IntegerField(validators=[MinValueValidator(0)])
    price = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        validators=[MinValueValidator(0)],
    )

    def __str__(self) -> str:
        """Return a string representation of the product."""
        return f"{self.name} {self.price}€/{self.weight}g"

manager/views/product_editor_view.py
from django.forms import ValidationError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.http import require_POST, require_safe

from manager.models import Category, Product
from django.contrib import messages


@require_safe
def product_editor(request: HttpRequest) -> HttpResponse:
    context = {"shop_choices": Product.Shops.labels}
    return render(request, "product/product_editor.html", context=context)


@require_POST
def create_new_product(request: HttpRequest) -> HttpResponse:
    try:
        product_name = request.POST["product_name"]
        shop = request.POST["shop"]
        url = request.POST["url"]
        weight = request.POST["weight"]
        price = request.POST["price"]
    except MultiValueDictKeyError as e:
        messages.error(request, str(e))
        return redirect("manager:product_editor")

    product = Product(
        name=product_name,
        shop=shop,
        url=url,
        weight=weight,
        price=price,
    )

    try:
        product.full_clean()
    except ValidationError as e:
        messages.error(request, str(e))
        return redirect("manager:product_editor")

    product.save()

    return HttpResponseRedirect(reverse("manager:index"))

preisvergleich/views/category_detail_view.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from preisvergleich.models import Category


def category_detail(
    request: HttpRequest,
    category_id: int,
) -> HttpResponse:
    category = get_object_or_404(Category, pk=category_id)

    context = {"category": category}

    return render(request, "category/category_detail.html", context)

preisvergleich/views/category_editor_view.py
from django.contrib import messages
from django.forms import ValidationError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_POST, require_safe

from preisvergleich.models import Category

CATEGORY_EDITOR_HTML = "category/category_editor.html"


@require_safe
def category_editor(request: HttpRequest) -> HttpResponse:
    context = {
        "category_name": request.session.get("category_name", ""),
    }
    return render(request, CATEGORY_EDITOR_HTML, context)


@require_POST
def create_new_category(request: HttpRequest) -> HttpResponse:

    category_name = request.POST.get("category_name", "")
    request.session["category_name"] = category_name

    if not category_name:
        messages.error(request, "Category name is required.")
        context = {"category_name": category_name}
        return render(request, CATEGORY_EDITOR_HTML, context=context)

    category = Category(
        name=category_name,
    )

    try:
        category.full_clean()
    except ValidationError as e:
        messages.error(request, e.messages)
        context = {"category_name": category_name}
        return render(request, CATEGORY_EDITOR_HTML, context=context)

    category.save()
    request.session.clear()
    return HttpResponseRedirect(reverse("preisvergleich:index"))

preisvergleich/views/helper_views.py
from django.http import HttpRequest, HttpResponse
from django.views.decorators.http import require_POST


@require_POST
def delete_error_message(_: HttpRequest) -> HttpResponse:
    return HttpResponse("")

preisvergleich/views/index_view.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_safe

from preisvergleich.models import Category


@require_safe
def index(request: HttpRequest) -> HttpResponse:
    categories = Category.objects.all()
    context = {
        "category_list": categories,
    }

    return render(request, "index.html", context)

preisvergleich/views/product_editor_view.py
from django.contrib import messages
from django.forms import ValidationError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.http import require_POST, require_safe

from preisvergleich.models import Category, Product


@require_safe
def product_editor(request: HttpRequest, category_id: int) -> HttpResponse:
    category = get_object_or_404(Category, pk=category_id)
    context = {
        "shop_choices": Product.Shops.labels,
        "product_name": request.session.get("product_name", ""),
        "shop": request.session.get("shop", ""),
        "url": request.session.get("url", ""),
        "weight": request.session.get("weight", ""),
        "price": request.session.get("price", ""),
        "category_id": category.id,
    }
    return render(request, "product/product_editor.html", context=context)


@require_POST
def create_new_product(request: HttpRequest, category_id: int) -> HttpResponse:
    category = get_object_or_404(Category, pk=category_id)
    try:
        product_name = request.POST["product_name"]
        shop = request.POST["shop"]
        url = request.POST["url"]
        weight = request.POST["weight"]
        price = request.POST["price"]

        request.session["product_name"] = product_name
        request.session["shop"] = shop
        request.session["url"] = url
        request.session["weight"] = weight
        request.session["price"] = price
    except MultiValueDictKeyError as e:
        messages.error(request, str(e))
        return redirect("preisvergleich:product_editor", category_id=category_id)

    product = Product(
        category=category,
        name=product_name,
        shop=shop,
        url=url,
        weight=weight,
        price=price,
    )

    try:
        product.full_clean()
    except ValidationError as e:
        messages.error(request, str(e))
        return redirect("preisvergleich:product_editor", category_id=category_id)

    product.save()
    request.session.clear()

    return HttpResponseRedirect(reverse("preisvergleich:index"))

preisvergleich/templates/product/product_editor.html
{% extends "base.html" %}

{% block content %}
<div class="m-6">
  <form action="{% url 'preisvergleich:create_new_product' category_id %}" method="post">
    {% csrf_token %}

    {% if messages %}
    {% for message in messages %}
    <article class="message is-danger" id="error_box_{{ forloop.counter }}">
      <div class="message-header">
        <p>Error</p>
        <button class="delete" aria-label="delete" hx-post="{% url 'preisvergleich:delete_error_message' %}"
          hx-swap="outerHTML" hx-target="#error_box_{{ forloop.counter }}"></button>
      </div>
      <div class="message-body">
        {{ message }}
      </div>
    </article>
    {% endfor %}
    {% endif %}

    <div class="field">
      <label class="label">
        Product Name
        <div class="control">
          <input class="input" type="text" placeholder="Product Name" name="product_name" value="{{ product_name }}">
        </div>
      </label>
    </div>

    <div class="field">
      <label class="label">
        Shop
        <div class="control">
          <div class="select">
            <select name="shop">
              {% for shop_choice in shop_choices %}
              <option {% if shop_choice==shop %}selected{% endif %}>{{ shop_choice }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </label>
    </div>

    <div class="field">
      <label class="label">
        URL
        <div class="control">
          <input class="input" type="text" placeholder="URL" name="url" value="{{ url }}">
        </div>
      </label>
    </div>

    <div class="field">
      <label class="label">
        Weight
        <div class="control">
          <input class="input" type="text" placeholder="Weight" name="weight" value="{{ weight }}">
        </div>
      </label>
    </div>

    <div class="field">
      <label class="label">
        Price
        <div class="control">
          <input class="input" type="text" placeholder="Price" name="price" value="{{ price }}">
        </div>
      </label>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <button class="button is-link">Submit</button>
      </div>
      <div class="control">
        <button class="button is-link is-light">Cancel</button>
      </div>
    </div>

  </form>
</div>
{% endblock %}